# Generated by Django 4.2.3 on 2023-08-03 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
    ]
